### ISSUE TITLE
Could you do Lua 5.3?

### ISSUE THREAD

**Issue by PhilipRoman** [bkiers/lua-parser#1]
I need a Lua 5.3 parser in Java, but haven't been able to find one. I'd love to do it myself, but I'm not too good with this stuff. AFAIK the only syntax differences are only a few new operators:
- `x ~ y (bitwise xor)`
- `~x`
- `x | y`
- `x & y`
- `x << y`
- `x >> y`
- `x // y (floor division)`

Could you do this?

**Comment by bkiers** [comment]
Here you go: https://github.com/bkiers/lua-parser/pull/2

**Comment by PhilipRoman** [comment]
Awesome! :+1:
